code_name: X
with_suffix: ''
seed: 0
device: cuda
train_dir: ../cache/train2014/
batch_size: 4
accelerate: true
torch_dtype_str: float32
img_size: 256
steps: 100000
warmup_steps: 1000
optimizer: AdamW,lr=1e-4
cosine_lr: false
bit_length: 48
loss_w: bce
loss_i: watson-vgg
lambda_w: 1.0
lambda_i: 0.2
i2_trick: false
distortion: false
i_constraint: -1.0
log_with_wandb: true
log_freq: 10
save_img_freq: 50
save_checkpoint_freq: 2000
model_id: ../cache/sdxl-turbo
local_files_only: true
use_safetensors: true
use_cached_latents: false
use_ldm_decoder_checkpoint: ''
the_force: 0.01
pipeline_parallel: false
parallel_gpu_num: 2
parallel_split_size: 2
granularity: kernel
layer_selection: layer_range
layer_begin: up_blocks.1.resnets.0.conv1
layer_end: up_blocks.3.resnets.0.conv1
use_lora: true
lora_rank: 8
channel_selection: random
include_bias: false
chain: true
total_group_num: 32
group_num: 32
start_group: 11
conv_out_full_out: false
use_backbone: true
hidden_dims: []
use_batchnorm: false
use_msg_decoder_checkpoint: pretrained/dec_48b_whit.torchscript.pt
train_msg_decoder: false
msg_decoder_track_running_stats: false
msg_decoder_hidden_channels: 64
msg_decoder_hidden_depth: 8
msg_decoder_hidden_redundancy: 1
validate: true
val_img_size: 512
val_img_num: 80
val_save_img_freq: 1
val_batch_size: 4
val_dir: ../cache/val2014/
